# Redirect www to non-www and strip trailing slashes
[[redirects]]
  from = "https://www.rosterlab.com/*/"
  to = "https://rosterlab.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.rosterlab.com/*"
  to = "https://rosterlab.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.rosterlab.com/*/"
  to = "https://rosterlab.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.rosterlab.com/*"
  to = "https://rosterlab.com/:splat"
  status = 301
  force = true

# Redirect http to https (for non-www)
[[redirects]]
  from = "http://rosterlab.com/*"
  to = "https://rosterlab.com/:splat"
  status = 301
  force = true
