import type { IndustryConfig } from "@/lib/pdf-generator";

export const industryConfigs: Record<string, IndustryConfig> = {
  nursing: {
    name: "Nursing",
    schedulingComplexity: 1.2,
    overtimeReduction: 0.45,
    turnoverReduction: 0.3,
    defaultOvertime: 8,
    defaultTurnover: 15,
    defaultEmployees: 40,
    defaultHourlyWage: 60,
    defaultCycleWeeks: 4,
    defaultRosteringDays: 4,
    implementationDays: 3,
    // Saving categories
    hasManualTimeSaving: true,
    hasStaffingEfficiency: true,
    hasSkillMix: false,
    hasTurnover: true,
    // Staffing efficiency data
    avgSalary: 91179,
    avgFTE: 0.86,
    inefficiency: 0.03,
    baseCost: 2352,
    baseSaving: 470.48,
    overtimePenalty: 1.2,
    overtimeCost: 847,
    locumEfficiency: 1.2,
    locumCost: 423,
    totalSaving: 3623,
    // Skill mix data
    lowestPay: 242249,
    highestPay: 488593,
    weekendPenalty: 1.2,
    weekendShiftCost: 22171,
    weekendSaving: 2217,
    nightPenalty: 1.2,
    nightShiftCost: 27919,
    nightSaving: 2792,
    skillMixTotalPerStaff: 5009,
    // Turnover data
    turnoverCostPerRole: 30000,
    turnoverRate: 0.15,
    turnoverImprovement: 0.05,
    hiringAdminCost: 230,
    turnoverTotalSaving: 9180,
    // Leave balance data
    annualLeaveCost: 385,
    annualLeaveReduction: 0.3,
    sickLeaveTotal: 7692,
    sickLeaveReduction: 0.1,
    leaveSavingPerStaff: 884.62,
  },
  "acute-specialties": {
    name: "Acute",
    schedulingComplexity: 1.35,
    overtimeReduction: 0.45,
    turnoverReduction: 0.25,
    defaultOvertime: 9,
    defaultTurnover: 8,
    defaultEmployees: 50,
    defaultHourlyWage: 130,
    defaultCycleWeeks: 12,
    defaultRosteringDays: 10,
    implementationDays: 4,
    // Saving categories
    hasManualTimeSaving: true,
    hasStaffingEfficiency: true,
    hasSkillMix: false,
    hasTurnover: true,
    // Staffing efficiency data
    avgSalary: 150000,
    avgFTE: 0.9,
    inefficiency: 0.015,
    baseCost: 2025,
    baseSaving: 405,
    overtimePenalty: 1.2,
    overtimeCost: 729,
    locumEfficiency: 1.2,
    locumCost: 365,
    totalSaving: 3119,
    // Skill mix data
    lowestPay: 238498,
    highestPay: 471906,
    weekendPenalty: 1.2,
    weekendShiftCost: 21007,
    weekendSaving: 2101,
    nightPenalty: 1.2,
    nightShiftCost: 26453,
    nightSaving: 2645,
    skillMixTotalPerStaff: 4746,
    // Turnover data
    turnoverCostPerRole: 80000,
    turnoverRate: 0.08,
    turnoverImprovement: 0.05,
    hiringAdminCost: 320,
    turnoverTotalSaving: 16000,
    // Leave balance data
    annualLeaveCost: 385,
    annualLeaveReduction: 0.3,
    sickLeaveTotal: 7692,
    sickLeaveReduction: 0.1,
    leaveSavingPerStaff: 884.62,
  },
  "medicine-specialties": {
    name: "Medicine",
    schedulingComplexity: 1.3,
    overtimeReduction: 0.4,
    turnoverReduction: 0.2,
    defaultOvertime: 7,
    defaultTurnover: 12,
    defaultEmployees: 40,
    defaultHourlyWage: 130,
    defaultCycleWeeks: 12,
    defaultRosteringDays: 8,
    implementationDays: 5,
    // Saving categories
    hasManualTimeSaving: true,
    hasStaffingEfficiency: true,
    hasSkillMix: false,
    hasTurnover: true,
    // Staffing efficiency data
    avgSalary: 150000,
    avgFTE: 0.9,
    inefficiency: 0.015,
    baseCost: 2025,
    baseSaving: 405,
    overtimePenalty: 1.3,
    overtimeCost: 790,
    locumEfficiency: 1.3,
    locumCost: 395,
    totalSaving: 3210,
    // Skill mix data
    lowestPay: 302900,
    highestPay: 635996,
    weekendPenalty: 1.2,
    weekendShiftCost: 29979,
    weekendSaving: 2998,
    nightPenalty: 1.2,
    nightShiftCost: 37751,
    nightSaving: 3775,
    skillMixTotalPerStaff: 6773,
    // Turnover data
    turnoverCostPerRole: 80000,
    turnoverRate: 0.12,
    turnoverImprovement: 0.05,
    hiringAdminCost: 480,
    turnoverTotalSaving: 19200,
    // Leave balance data
    annualLeaveCost: 385,
    annualLeaveReduction: 0.3,
    sickLeaveTotal: 7692,
    sickLeaveReduction: 0.1,
    leaveSavingPerStaff: 884.62,
  },
  "allied-health": {
    name: "Allied Health",
    schedulingComplexity: 1.25,
    overtimeReduction: 0.4,
    turnoverReduction: 0.2,
    defaultOvertime: 6,
    defaultTurnover: 18,
    defaultEmployees: 80,
    defaultHourlyWage: 60,
    defaultCycleWeeks: 4,
    defaultRosteringDays: 9,
    implementationDays: 5,
    // Saving categories
    hasManualTimeSaving: true,
    hasStaffingEfficiency: true,
    hasSkillMix: false,
    hasTurnover: true,
    // Staffing efficiency data
    avgSalary: 100000,
    avgFTE: 0.9,
    inefficiency: 0.02,
    baseCost: 1800,
    baseSaving: 360,
    overtimePenalty: 1.2,
    overtimeCost: 648,
    locumEfficiency: 1.2,
    locumCost: 324,
    totalSaving: 2772,
    // Skill mix data
    lowestPay: 70690,
    highestPay: 121356,
    weekendPenalty: 1.5,
    weekendShiftCost: 5700,
    weekendSaving: 570,
    nightPenalty: 1.25,
    nightShiftCost: 5981,
    nightSaving: 598,
    skillMixTotalPerStaff: 1168,
    // Turnover data
    turnoverCostPerRole: 40000,
    turnoverRate: 0.18,
    turnoverImprovement: 0.1,
    hiringAdminCost: 720,
    turnoverTotalSaving: 36000,
    // Leave balance data
    annualLeaveCost: 385,
    annualLeaveReduction: 0.3,
    sickLeaveTotal: 3846,
    sickLeaveReduction: 0.1,
    leaveSavingPerStaff: 500.0,
  },
  midwives: {
    name: "Midwives",
    schedulingComplexity: 1.2,
    overtimeReduction: 0.4,
    turnoverReduction: 0.25,
    defaultOvertime: 7,
    defaultTurnover: 15,
    defaultEmployees: 50,
    defaultHourlyWage: 60,
    defaultCycleWeeks: 4,
    defaultRosteringDays: 4,
    implementationDays: 3,
    // Saving categories
    hasManualTimeSaving: true,
    hasStaffingEfficiency: true,
    hasSkillMix: false,
    hasTurnover: true,
    // Staffing efficiency data
    avgSalary: 110000,
    avgFTE: 0.8,
    inefficiency: 0.015,
    baseCost: 1320,
    baseSaving: 264,
    overtimePenalty: 1.2,
    overtimeCost: 475,
    locumEfficiency: 1.2,
    locumCost: 238,
    totalSaving: 2033,
    // Skill mix data
    lowestPay: 90000,
    highestPay: 130000,
    weekendPenalty: 1.5,
    weekendShiftCost: 4500,
    weekendSaving: 450,
    nightPenalty: 1.25,
    nightShiftCost: 4722,
    nightSaving: 472,
    skillMixTotalPerStaff: 922,
    // Turnover data
    turnoverCostPerRole: 30000,
    turnoverRate: 0.15,
    turnoverImprovement: 0.05,
    hiringAdminCost: 225,
    turnoverTotalSaving: 11250,
    // Leave balance data
    annualLeaveCost: 385,
    annualLeaveReduction: 0.3,
    sickLeaveTotal: 3846,
    sickLeaveReduction: 0.1,
    leaveSavingPerStaff: 500.0,
  },
  veterinary: {
    name: "Veterinary",
    schedulingComplexity: 1.2,
    overtimeReduction: 0.4,
    turnoverReduction: 0.25,
    defaultOvertime: 7,
    defaultTurnover: 14,
    defaultEmployees: 50,
    defaultHourlyWage: 60,
    defaultCycleWeeks: 4,
    defaultRosteringDays: 4,
    implementationDays: 3,
    // Saving categories
    hasManualTimeSaving: true,
    hasStaffingEfficiency: true,
    hasSkillMix: false,
    hasTurnover: true,
    // Staffing efficiency data
    avgSalary: 110000,
    avgFTE: 0.85,
    inefficiency: 0.02,
    baseCost: 1870,
    baseSaving: 374,
    overtimePenalty: 1.2,
    overtimeCost: 673,
    locumEfficiency: 1.2,
    locumCost: 337,
    totalSaving: 2880,
    // Skill mix data
    lowestPay: 90000,
    highestPay: 130000,
    weekendPenalty: 1.5,
    weekendShiftCost: 4500,
    weekendSaving: 450,
    nightPenalty: 1.25,
    nightShiftCost: 4722,
    nightSaving: 472,
    skillMixTotalPerStaff: 922,
    // Turnover data
    turnoverCostPerRole: 80000,
    turnoverRate: 0.14,
    turnoverImprovement: 0.05,
    hiringAdminCost: 560,
    turnoverTotalSaving: 28000,
    // Leave balance data
    annualLeaveCost: 385,
    annualLeaveReduction: 0.3,
    sickLeaveTotal: 3846,
    sickLeaveReduction: 0.1,
    leaveSavingPerStaff: 500.0,
  },
  surgical: {
    name: "Surgical",
    schedulingComplexity: 1.3,
    overtimeReduction: 0.4,
    turnoverReduction: 0.2,
    defaultOvertime: 7,
    defaultTurnover: 12,
    defaultEmployees: 30,
    defaultHourlyWage: 120,
    defaultCycleWeeks: 4,
    defaultRosteringDays: 3,
    implementationDays: 4,
    // Saving categories
    hasManualTimeSaving: true,
    hasStaffingEfficiency: true,
    hasSkillMix: false,
    hasTurnover: true,
    // Staffing efficiency data
    avgSalary: 250000,
    avgFTE: 0.9,
    inefficiency: 0.01,
    baseCost: 2250,
    baseSaving: 450,
    overtimePenalty: 1.1,
    overtimeCost: 743,
    locumEfficiency: 1.1,
    locumCost: 371,
    totalSaving: 3364,
    // Skill mix data
    lowestPay: 200000,
    highestPay: 300000,
    weekendPenalty: 1.5,
    weekendShiftCost: 10000,
    weekendSaving: 1000,
    nightPenalty: 1.25,
    nightShiftCost: 10500,
    nightSaving: 1050,
    skillMixTotalPerStaff: 2050,
    // Turnover data
    turnoverCostPerRole: 80000,
    turnoverRate: 0.12,
    turnoverImprovement: 0.02,
    hiringAdminCost: 192,
    turnoverTotalSaving: 19200,
    // Leave balance data
    annualLeaveCost: 385,
    annualLeaveReduction: 0.3,
    sickLeaveTotal: 3846,
    sickLeaveReduction: 0.1,
    leaveSavingPerStaff: 500.0,
  },
  "aged-care": {
    name: "Aged care",
    schedulingComplexity: 1.1,
    overtimeReduction: 0.4,
    turnoverReduction: 0.3,
    defaultOvertime: 6,
    defaultTurnover: 25,
    defaultEmployees: 60,
    defaultHourlyWage: 40,
    defaultCycleWeeks: 2,
    defaultRosteringDays: 3,
    implementationDays: 3,
    // Saving categories
    hasManualTimeSaving: true,
    hasStaffingEfficiency: true,
    hasSkillMix: false,
    hasTurnover: true,
    // Staffing efficiency data
    avgSalary: 65000,
    avgFTE: 0.8,
    inefficiency: 0.03,
    baseCost: 1560,
    baseSaving: 312,
    overtimePenalty: 1.5,
    overtimeCost: 702,
    locumEfficiency: 1.5,
    locumCost: 351,
    totalSaving: 2613,
    // Skill mix data
    lowestPay: 66666,
    highestPay: 95238,
    weekendPenalty: 1.5,
    weekendShiftCost: 5417,
    weekendSaving: 542,
    nightPenalty: 1.25,
    nightShiftCost: 5684,
    nightSaving: 568,
    skillMixTotalPerStaff: 1110,
    // Turnover data
    turnoverCostPerRole: 10000,
    turnoverRate: 0.25,
    turnoverImprovement: 0.1,
    hiringAdminCost: 250,
    turnoverTotalSaving: 15000,
    // Leave balance data
    annualLeaveCost: 385,
    annualLeaveReduction: 0.3,
    sickLeaveTotal: 2885,
    sickLeaveReduction: 0.1,
    leaveSavingPerStaff: 403.85,
  },
};
